services:
  app:
    image: ghcr.io/yudhnaa/personal-tracker:latest
    container_name: personal-tracker-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - default
      - homelab

networks:
  homelab:
    external: true
